### ISSUE TITLE
Android SDK license not accepted

### ISSUE THREAD

**Issue by jeanpierrefortune** [thedrhax-dockerfiles/android-sdk#2]
Hi,
We have been using this docker file successfully for several months.
For no apparent reason, the Android build now fails with the following error:
```
File /home/user/.android/repositories.cfg could not be loaded.
Checking the license for package Android SDK Build-Tools 26.0.2 in /home/user/android-sdk-linux/licenses
Warning: License for package Android SDK Build-Tools 26.0.2 not accepted.
Checking the license for package Android SDK Platform 26 in /home/user/android-sdk-linux/licenses
Warning: License for package Android SDK Platform 26 not accepted.

FAILURE: Build failed with an exception.
```
Any ideas on how to solve this?

**Comment by jeanpierrefortune** [comment]
Seems to be related to this
https://issuetracker.google.com/issues/123054726

**Comment by TheDrHax** [comment]
Hi,

I have rebuilt the image on Docker Hub. Looks like it is working good again. Could you please test it?

```
docker pull thedrhax/android-sdk
```

**Comment by jeanpierrefortune** [comment]
Hi,

Everything now works like a charm on my side!

Thank you very much!
